CREATE TABLE IF NOT EXISTS company_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  company_name TEXT NOT NULL DEFAULT '',
  address_line1 TEXT,
  address_line2 TEXT,
  gstin TEXT,
  phone TEXT,
  email TEXT,
  bank_name TEXT,
  bank_account TEXT,
  bank_ifsc TEXT,
  terms_line1 TEXT,
  terms_line2 TEXT,
  default_state_label TEXT NOT NULL DEFAULT 'State',
  cgst_rate REAL NOT NULL DEFAULT 2.5,
  sgst_rate REAL NOT NULL DEFAULT 2.5,
  igst_rate REAL NOT NULL DEFAULT 5.0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO company_settings (
  id,
  company_name,
  address_line1,
  address_line2,
  gstin,
  phone,
  email,
  bank_name,
  bank_account,
  bank_ifsc,
  terms_line1,
  terms_line2,
  default_state_label,
  cgst_rate,
  sgst_rate,
  igst_rate
) VALUES (
  1,
  'KAMAL READYMADE STORES',
  'Shop No 7, 1st Floor Deluxe Chamber',
  'Mirghawad Ahmedabad - 380001',
  '24AAFPL5557N1ZA',
  '079 22174580, 9374159220, 9426029197',
  'sureshklalwani1@gmail.com',
  'KOTAK MAHINDRA BANK',
  '4413075389',
  'KKBK0002580',
  'Goods once sold will not be taken back.',
  'Interest @18% p.a. will be charged if payment is not made within the due date.',
  'State',
  2.5,
  2.5,
  5.0
);
